ServerEvents.tags('item', event => {
    event.add('c:hidden_from_recipe_viewers', 'utopia:incomplete_netherite_helmet')
    event.add('c:hidden_from_recipe_viewers', 'utopia:incomplete_netherite_chestplate')
    event.add('c:hidden_from_recipe_viewers', 'utopia:incomplete_netherite_leggings')
    event.add('c:hidden_from_recipe_viewers', 'utopia:incomplete_netherite_boots')
    event.add('c:hidden_from_recipe_viewers', 'utopia:shattered_crown')

    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:glow_berry_jam_toast')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:glow_berry_jam')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:sweet_berry_jam_toast')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:sweet_berry_jam')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:toast')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:dough')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:knife')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:cheese')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:wheat_flour')
    event.add('c:hidden_from_recipe_viewers', 'refurbished_furniture:recycling_bin')
    event.add('c:hidden_from_recipe_viewers', 'brewinandchewin:pizza')
    event.add('c:hidden_from_recipe_viewers', 'farmersdelight:wheat_dough')
    event.add('c:hidden_from_recipe_viewers', 'vc_gliders:reinforced_paper_iron')
    event.add('c:hidden_from_recipe_viewers', 'vc_gliders:reinforced_paper_gold')
    event.add('c:hidden_from_recipe_viewers', 'vc_gliders:reinforced_paper_diamond')
    event.add('c:hidden_from_recipe_viewers', 'vc_gliders:reinforced_paper_netherite')
    event.add('c:hidden_from_recipe_viewers', 'naturalist:cooked_egg')
    event.add('c:hidden_from_recipe_viewers', 'frame_changer:crying_obsidian_brick_slab')
    event.add('c:hidden_from_recipe_viewers', 'frame_changer:crying_polished_obsidian_stairs')
    event.add('c:hidden_from_recipe_viewers', 'frame_changer:crying_obsidian_brick_stairs')
    event.add('c:hidden_from_recipe_viewers', 'frame_changer:crying_polished_obsidian')
    event.add('c:hidden_from_recipe_viewers', 'frame_changer:crying_polished_obsidian_wall')
    event.add('c:hidden_from_recipe_viewers', 'frame_changer:crying_obsidian_bricks')
    event.add('c:hidden_from_recipe_viewers', 'frame_changer:crying_obsidian_brick_wall')
    event.add('c:hidden_from_recipe_viewers', 'frame_changer:crying_polished_obsidian_slab')
    event.add('c:hidden_from_recipe_viewers', 'artifacts:eternal_steak')
    event.add('c:hidden_from_recipe_viewers', 'artifacts:everlasting_beef')
    event.add('c:hidden_from_recipe_viewers', 'supplementaries:quark/way_sign_ancient')
    event.add('c:hidden_from_recipe_viewers', 'supplementaries:quark/cannon_boat_ancient')
    event.add('c:hidden_from_recipe_viewers', 'supplementaries:quark/ancient_boat')

})
