items {
    # Format: "modid:item_name"=durability
    # Examples:
    # "minecraft:diamond_sword"=750
    # "minecraft:netherite_sword"=1250
    "minecraft:trident"=325
    "minecraft:golden_sword"=225
    "minecraft:golden_axe"=225
    "minecraft:golden_pickaxe"=225
    "minecraft:golden_shovel"=225
    "minecraft:golden_hoe"=225

    "minecraft:golden_helmet"=152
    "minecraft:golden_chestplate"=220
    "minecraft:golden_leggings"=206
    "minecraft:golden_boots"=179
}
