#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 28 20:45:21 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=ComplementaryReimagined_r5.9.3.zip
