#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 23 21:05:56 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit) + Clrwl_1.0.5.zip
