# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				pale_oak_boat = true
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				happy_ghast = true
				drowned = true
				creaking = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				block_display = true
				tnt_minecart = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				pale_oak_chest_boat = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				sulfur_cube = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.astikorcartsredux]
				plow = true
				supply_cart = true
				postilion = true
				animal_cart = true
				hand_cart = true
				reaper = true
				seed_drill = true

			[light_sources.settings.entities.endermanoverhaul]
				flower_fields_enderman = true
				coral_enderman = true
				ender_bullet = true
				windswept_hills_enderman = true
				icy_pearl = true
				summoner_pearl = true
				nether_wastes_enderman = true
				soul_pearl = true
				mushroom_fields_enderman = true
				snowy_enderman = true
				soulsand_valley_enderman = true
				axolotl_pet_enderman = true
				hammerhead_pet_enderman = true
				savanna_enderman = true
				ice_spikes_enderman = true
				desert_enderman = true
				spirit = true
				ancient_pearl = true
				end_enderman = true
				corrupted_pearl = true
				bubble_pearl = true
				crimson_forest_enderman = true
				warped_pearl = true
				cave_enderman = true
				dark_oak_enderman = true
				crimson_pearl = true
				end_islands_enderman = true
				scarab = true
				swamp_enderman = true
				badlands_enderman = true
				warped_forest_enderman = true
				pet_enderman = true

			[light_sources.settings.entities.oreganized]
				shrapnel_bomb = true
				lead_bolt = true
				shrapnel_bomb_minecart = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				rhino = true
				bluejay = true
				snake = true
				catfish = true
				boar = true
				caterpillar = true
				dragonfly = true
				robin = true
				duck_egg = true
				tortoise = true
				butterfly = true
				duck = true
				bear = true
				sparrow = true
				lizard = true
				rattlesnake = true
				zebra = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				lizard_tail = true
				elephant = true
				finch = true

			[light_sources.settings.entities.spearsmod]
				golden_spear = true
				spear = true
				diamond_spear = true
				stone_spear = true
				netherite_spear = true
				wooden_spear = true
				iron_spear = true

			[light_sources.settings.entities.quark]
				quark_boat = true
				dyed_item_frame = true
				stool = true
				skull_pike = true
				toretoise = true
				gravisand = true
				parrot_egg = true
				foxhound = true
				stoneling = true
				torch_arrow = true
				wraith = true
				shiba = true
				totem = true
				forgotten = true
				quark_chest_boat = true
				glass_frame = true
				crab = true
				pickarang = true
				soul_bead = true
				flamerang = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.etched]
				jukebox_minecart = true

			[light_sources.settings.entities.pet_cemetery]
				skeleton_wolf = true
				zombie_parrot = true
				skeleton_parrot = true
				zombie_cat = true
				skeleton_cat = true
				zombie_wolf = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.parcool]
				zipline_rope = true

			[light_sources.settings.entities.nirvana]
				reefer = true
				thc_minecart = true
				thc = true

			[light_sources.settings.entities.musketmod]
				bullet = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.royalvariations]
				royal_arrow = true
				royal_bomb_projectile = true
				royal_bomb = true
				royal_skeleton = true
				spectral_anvil = true
				royal_zombie = true
				royal_ender_pearl = true
				royal_enderman = true
				royal_creeper = true
				net = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				cave_creeper = true
				beach_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				birch_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.takesapillage]
				legioner = true
				archer = true
				skirmisher = true
				clay_golem = true

			[light_sources.settings.entities.refurbished_furniture]
				seat = true

			[light_sources.settings.entities.blueprint]
				falling_block = true
				chest_boat = true
				boat = true

			[light_sources.settings.entities.enhancedai]
				thrown_web = true
				fishing_hook = true

			[light_sources.settings.entities.exposure]
				glass_photograph_frame = true
				camera_stand = true
				photograph_frame = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				brick_projectile = true
				plunderer = true
				falling_sack = true
				pearl_marker = true
				hat_stand = true
				bomb = true
				falling_ash = true
				cannonball = true
				falling_urn = true
				red_merchant = true
				cannon_boat = true
				rope_arrow = true
				slimeball_projectile = true

			[light_sources.settings.entities.corpse]
				corpse = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
