version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "CHECK"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
naturalist = true
oreganized = true
farmersdelight = true
supplementaries = true
backpacked = true
barteringstation = true
storagedrawers = true
alexsmobs = true
someassemblyrequired = true
createtransmission = true
create = true
frame_changer = true
easymagic = true
brewinandchewin = true
etched = true
quark = true
alexscaves = true
easyanvils = true
refurbished_furniture = true
sereneseasons = true
minecraft = true
diy_campfires = true
create_dragons_plus = true
comforts = true
citadel = true
endermanoverhaul = true
creeperoverhaul = true
nirvana = true
stockmarket = true
createcobblestone = true
create_bb = true
parcool = true
moonlight = true
utopia = true
treechop = true
tradeworks = true
exposure = true
endanchor = true
