version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "GAP"
leavesCullingAmount = 2
includeMangroveRoots = false
endGatewayCulling = false
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
oreganized = true
farmersdelight = true
supplementaries = true
backpacked = true
alexsmobs = true
storagedrawers = true
create = true
easymagic = true
brewinandchewin = true
quark = true
alexscaves = true
easyanvils = true
refurbished_furniture = true
sereneseasons = true
minecraft = true
diy_campfires = true
create_dragons_plus = true
comforts = true
citadel = true
endermanoverhaul = true
createcobblestone = true
creeperoverhaul = true
nirvana = true
parcool = true
moonlight = true
tradeworks = true
exposure = true
endanchor = true
