[ore_generation]
	#Multiplier for ore vein size
	# Default: 0.5
	# Range: 0.01 ~ 1.0
	ore_size_multiplier = 0.5
	#Chance for ore generation
	# Default: 0.5
	# Range: 0.01 ~ 1.0
	ore_generation_chance = 0.5
	#List of custom ore names that should be affected (e.g. ore_ancient_debris)
	#Format: modid:ore_name or just ore_name for minecraft
	custom_ores = ["ore_ancient_debris"]
	#List of ore names that should be EXCLUDED from reduction.
	#Format: modid:ore_name or just ore_name for minecraft
	excluded_ores = []
