StartupEvents.registry('item', event => {
    event.create('utopia:ruby').displayName('Ruby').texture('utopia:item/ruby').tag('c:gems/ruby').tag('c:ruby')
})

StartupEvents.registry('block', event => {
  event.create('utopia:ruby_block')
    .displayName('Block of Ruby')
    .soundType('metal')
    .hardness(4.0)
    .resistance(5.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')

  event.create('utopia:ruby_ore')
    .displayName('Ruby Ore')
    .soundType('stone')
    .hardness(3.0)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBoth('c:ores')
    .tagBoth('c:ores/ruby')

  event.create('utopia:deepslate_ruby_ore')
    .displayName('Deepslate Ruby Ore')
    .soundType('deepslate')
    .hardness(4.5)
    .resistance(3.0)
    .requiresTool(true)
    .tagBlock('minecraft:mineable/pickaxe')
    .tagBlock('minecraft:needs_iron_tool')
    .tagBoth('c:ores')
    .tagBoth('c:ores/ruby') 
})